import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "secondary": "#a0401c",
        "on-secondary-fixed": "#390c00",
        "surface-canvas": "#FBF9F5",
        "surface-bright": "#f8faf8",
        "surface-container-low": "#f2f4f2",
        "on-primary-fixed": "#002111",
        "surface": "#f8faf8",
        "risk-low-subtle": "#EFF3F0",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#2b4966",
        "error-container": "#ffdad6",
        "risk-high": "#E66A1F",
        "primary-fixed-dim": "#95d4ac",
        "state-resolved": "#0E7A45",
        "risk-medium": "#D48806",
        "on-secondary-container": "#722200",
        "surface-card": "#FFFFFF",
        "on-primary": "#ffffff",
        "surface-container-high": "#e7e9e6",
        "risk-medium-subtle": "#FEF7E6",
        "inverse-on-surface": "#f0f1ef",
        "surface-variant": "#e1e3e1",
        "background": "#f8faf8",
        "risk-critical": "#D93829",
        "tertiary-fixed-dim": "#abc9ec",
        "secondary-fixed-dim": "#ffb59c",
        "on-tertiary-container": "#9ab8da",
        "tertiary": "#11324e",
        "risk-low": "#526B5C",
        "outline-variant": "#c0c9c0",
        "surface-tint": "#2d6a48",
        "surface-container": "#edeeec",
        "tertiary-container": "#2b4966",
        "on-primary-fixed-variant": "#0f5132",
        "surface-container-highest": "#e1e3e1",
        "on-surface": "#191c1b",
        "secondary-container": "#fe875d",
        "inverse-primary": "#95d4ac",
        "on-secondary-fixed-variant": "#802a05",
        "risk-critical-subtle": "#FDECEB",
        "on-surface-variant": "#404942",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#84c39b",
        "primary-fixed": "#b0f1c7",
        "surface-dim": "#d9dad8",
        "surface-subtle": "#F3EFEA",
        "outline": "#707971",
        "secondary-fixed": "#ffdbcf",
        "tertiary-fixed": "#cfe5ff",
        "state-resolved-subtle": "#E8F5EE",
        "risk-high-subtle": "#FEF0E6",
        "on-background": "#191c1b",
        "primary": "#003820",
        "primary-container": "#0f5132",
        "inverse-surface": "#2e3130",
        "on-tertiary-fixed": "#001d34",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "margin-mobile": "1.25rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "max-content-width": "42rem",
        "touch-target-min": "3rem",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        display: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        body: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
